spring.application.name=tortilla-cloud

server.port=8080

#for thymleaf config
spring.web.resources.static-locations=classpath:/static/
spring.thymeleaf.cache = false

#h2 db
spring.datasource.url=jdbc:h2:mem:tortilladb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

#jpa / hibernate
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true
spring.jpa.properties.hibernate.format_sql=true

#h2 con
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

#pagination
tortilla.orders.page-size=10